// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...flutterfire configure --project=momofy-a22be
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDKVbJl-9bHCC-xIXtPhwwotDQJSDTbOvc',
    appId: '1:376906976657:android:71cfe6e24e223343925e30',
    messagingSenderId: '376906976657',
    projectId: 'momofy-a22be',
    storageBucket: 'momofy-a22be.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBbS-X7onWkf-SThtyqT38Y7-MqnONe6mE',
    appId: '1:376906976657:ios:ee632cbab8910766925e30',
    messagingSenderId: '376906976657',
    projectId: 'momofy-a22be',
    storageBucket: 'momofy-a22be.appspot.com',
    androidClientId: '376906976657-0d6iu686bgbk9rl9mir5dvhi3stvncs2.apps.googleusercontent.com',
    iosClientId: '376906976657-0gro70nh5daqam597b6d822r5fe8v5gf.apps.googleusercontent.com',
    iosBundleId: 'com.example.momofy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDGz-m0MUbywslgTK5Sri00HEolNGXRnbU',
    appId: '1:376906976657:web:f0db1519ab486083925e30',
    messagingSenderId: '376906976657',
    projectId: 'momofy-a22be',
    authDomain: 'momofy-a22be.firebaseapp.com',
    storageBucket: 'momofy-a22be.appspot.com',
    measurementId: 'G-SCK214CZWM',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDGz-m0MUbywslgTK5Sri00HEolNGXRnbU',
    appId: '1:376906976657:web:7f5731a7f04dd3e7925e30',
    messagingSenderId: '376906976657',
    projectId: 'momofy-a22be',
    authDomain: 'momofy-a22be.firebaseapp.com',
    storageBucket: 'momofy-a22be.appspot.com',
    measurementId: 'G-ZZQ4R5SEHK',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBbS-X7onWkf-SThtyqT38Y7-MqnONe6mE',
    appId: '1:376906976657:ios:ee632cbab8910766925e30',
    messagingSenderId: '376906976657',
    projectId: 'momofy-a22be',
    storageBucket: 'momofy-a22be.appspot.com',
    androidClientId: '376906976657-0d6iu686bgbk9rl9mir5dvhi3stvncs2.apps.googleusercontent.com',
    iosClientId: '376906976657-0gro70nh5daqam597b6d822r5fe8v5gf.apps.googleusercontent.com',
    iosBundleId: 'com.example.momofy',
  );

}